theme {
    color_scheme = /usr/share/color-schemes/CatppuccinMochaFlamingo.colors
    style = kvantum-dark
    icon_theme = Breeze-Dark
    font = DepartureMono Nerd Font Mono
    font_fixed = DepartureMono Nerd Propo
    font_size = 9
    font_fixed_size = 9
}
